update github ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,23 +19,23 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
-      
+
     - name: Install apt-get packages
       run: |
         echo RESET grub-efi/install_devices | sudo debconf-communicate grub-pc
         sudo ACCEPT_EULA=Y apt-get update
         sudo ACCEPT_EULA=Y apt-get upgrade
         sudo apt-get install wget git curl software-properties-common build-essential
-    
+
     - name: Install Rust target for wasm
       run: |
         rustup target add wasm32-wasi
-        
+
     - name: Install WasmEdge
       run: |
         VERSION=0.12.1
         curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- -e all --version=$VERSION -p /usr/local
-    
+
     - name: sales_tax_rate
       run: |
         cd sales_tax_rate
@@ -58,6 +58,14 @@ jobs:
         resp=$(curl http://localhost:8002/compute -X POST -d @order.json)
         echo "$resp"
         if [[ $resp == *"21.65"* ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+        resp=$(curl http://localhost:8002/compute -X POST -d @order_zip_code_wrong.json)
+        echo "$resp"
+        if [[ $resp == *"error"* ]]; then
           echo -e "Execution Success!"
         else
           echo -e "Execution Fail!"
